version: "3.9"

services:
  redis:
    image: redis:latest
    volumes:
    - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
  rest: 
    build: app 
    ports: 
    - "127.0.0.1:5000:5000"
