version: "3.3"

services:
  redis:
    image: redis:latest
    networks:
    - rest-network
    volumes:
    - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
  rest: 
    build: app 
    ports: 
    - "5000:5000"
    networks:
    - rest-network
networks:
  rest-network:
    driver: bridge
